
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import UserProvider from './userProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogger',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider  >
          <Navbar/>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
